FAST_RCNN:
  ROI_BOX_HEAD: head_builder.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
FPN:
  FPN_ON: true
  MULTILEVEL_ROIS: true
  MULTILEVEL_RPN: true
MODEL:
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  FASTER_RCNN: true
  MASK_ON: true
  NUM_CLASSES: 3002
  TYPE: mask_rcnn
MRCNN:
  BBOX2MASK:
    BBOX2MASK_ON: true
    INCLUDE_BBOX_PRED: true
    STOP_DET_W_GRAD: true
    TYPE: 2_layer
  CONV_INIT: MSRAFill
  DILATION: 1
  JOINT_FCN_MLP_HEAD: true
  RESOLUTION: 28
  ROI_MASK_HEAD: mask_rcnn_heads.ResNet_mask_rcnn_fcn_head_v1up4convs
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
NUM_GPUS: 8
OUTPUT_DIR: .
TEST:
  DATASETS: ('vg3k_cocoaligned_val',)
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_POST_NMS_TOP_N: 1000
  RPN_PRE_NMS_TOP_N: 1000
  SCALE: 800
USE_NCCL: false
