FAST_RCNN:
  ROI_BOX_HEAD: head_builder.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
FPN:
  FPN_ON: true
  MULTILEVEL_ROIS: true
  MULTILEVEL_RPN: true
MODEL:
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  FASTER_RCNN: true
  MASK_ON: true
  NUM_CLASSES: 81
  TYPE: mask_rcnn
MRCNN:
  BBOX2MASK:
    BBOX2MASK_ON: true
    INCLUDE_BBOX_PRED: true
    STOP_DET_W_GRAD: true
    TYPE: 2_layer
  CONV_INIT: MSRAFill
  DILATION: 1
  JOINT_FCN_MLP_HEAD: true
  RESOLUTION: 28
  ROI_MASK_HEAD: mask_rcnn_heads.ResNet_mask_rcnn_fcn_head_v1up4convs
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
NUM_GPUS: 8
OUTPUT_DIR: .
SOLVER:
  BASE_LR: 0.02
  GAMMA: 0.1
  LR_POLICY: steps_with_decay
  MAX_ITER: 90000
  STEPS:
  - 0
  - 60000
  - 80000
  WEIGHT_DECAY: 0.0001
TEST:
  DATASETS: ('coco_2014_minival', 'coco_split_voc_2014_minival', 'coco_split_nonvoc_2014_minival')
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_POST_NMS_TOP_N: 1000
  RPN_PRE_NMS_TOP_N: 1000
  SCALE: 800
TRAIN:
  BATCH_SIZE_PER_IM: 512
  DATASETS: ('coco_2014_train', 'coco_2014_valminusminival')
  MAX_SIZE: 1333
  MRCNN_FILTER_LABELS: true
  MRCNN_LABELS_TO_KEEP: (8, 10, 11, 12, 13, 14, 21, 22, 23, 24, 25, 26, 27, 28, 29,
    30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
    51, 52, 53, 54, 55, 56, 60, 62, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
    76, 77, 78, 79, 80)
  RPN_PRE_NMS_TOP_N: 2000
  SCALES: (800,)
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
USE_NCCL: false
